services:
  vaultwarden:
    image: docker.io/vaultwarden/server@sha256:1587c45feaa479f1f5e8af3b00eded36bff77bcf1880cf8dbf0541706dd470e0
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: https://vault.gart.sh
    ports:
      - "100.114.67.239:4990:80"
    volumes:
      - /var/lib/vaultwarden/data:/data
