services:
  ntfy:
    image: docker.io/binwiederhier/ntfy@sha256:b8f8fb9ee044524d2baa303e5cfab4b3275378acf0b746bd9ace370a3b631a07
    container_name: ntfy
    restart: unless-stopped
    command: ["serve", "--cache-file", "/var/cache/ntfy/cache.db"]
    ports:
      - "100.114.67.239:8002:80"
    volumes:
      - /var/lib/ntfy/cache:/var/cache/ntfy
