services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:12@sha256:655c4a59e7868c56d573a636c7c71a6875e28bf1f4db3e78c5c19beacf92a2d0
    container_name: forgejo
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__DOMAIN=git.orcachill.in
      - FORGEJO__server__ROOT_URL=https://git.orcachill.in
      - FORGEJO__server__HTTP_ADDR=0.0.0.0
      - FORGEJO__server__HTTP_PORT=3000
      - FORGEJO__server__SSH_DOMAIN=git.orcachill.in
      - FORGEJO__server__START_SSH_SERVER=true
      - FORGEJO__server__SSH_PORT=2222
      - FORGEJO__server__SSH_LISTEN_PORT=2222
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__database__PATH=/data/forgejo.db
      - FORGEJO__security__INSTALL_LOCK=true
      - FORGEJO__actions__ENABLED=true
      - FORGEJO__packages__LIMIT_SIZE=-1
      - FORGEJO__oauth2__ENABLE=true
    ports:
      - "100.114.67.239:3000:3000"
      - "100.114.67.239:2222:2222"
    volumes:
      - /var/lib/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
