log:
  level: info

runner:
  capacity: 2
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s

container:
  network: "bridge"
  privileged: false
  options:
  workdir_parent:
  valid_volumes: []
  docker_host: "unix:///run/podman/podman.sock"

host:
  workdir_parent:
